# The Docker image to run your workspace in.
image:
  file: .gitpod.dockerfile

# Commands on:
tasks:
  # workspace initialization
  - init: >
      python3 -m pip install --upgrade pip &&
      python3 -m install -r requirements.txt
  # workspace startup  
    command: > 
      echo 'alias pip="pip3"' >> ~/.bashrc &&
      echo 'alias python="python3"' >> ~/.bashrc &&
      echo 'alias la="ls -la"' >> ~/.bashrc &&
      source ~/.bashrc
# Ports to expose
ports:
  - port: 8080

# Install vscode extensions
vscode:
  extensions:
    - ms-python.python
